using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WebApplication.Data;

#nullable disable

namespace WebApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260316203000_RecipeNormalization")]
    public partial class RecipeNormalization : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""RecipeIngredients"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""RecipeId"" integer NOT NULL,
    ""DisplayText"" text NOT NULL,
    ""SortOrder"" integer NOT NULL,
    CONSTRAINT ""FK_RecipeIngredients_Recipes_RecipeId"" FOREIGN KEY (""RecipeId"") REFERENCES ""Recipes"" (""Id"") ON DELETE CASCADE
);
");

            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""RecipeSteps"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""RecipeId"" integer NOT NULL,
    ""StepNumber"" integer NOT NULL,
    ""Description"" text NOT NULL,
    ""ImagePath"" text NOT NULL,
    CONSTRAINT ""FK_RecipeSteps_Recipes_RecipeId"" FOREIGN KEY (""RecipeId"") REFERENCES ""Recipes"" (""Id"") ON DELETE CASCADE
);
");

            migrationBuilder.Sql(@"
CREATE INDEX IF NOT EXISTS ""IX_RecipeIngredients_RecipeId"" ON ""RecipeIngredients"" (""RecipeId"");
CREATE INDEX IF NOT EXISTS ""IX_RecipeSteps_RecipeId"" ON ""RecipeSteps"" (""RecipeId"");
");

            // Move existing denormalized ingredient text into child rows.
            migrationBuilder.Sql(@"
INSERT INTO ""RecipeIngredients"" (""RecipeId"", ""DisplayText"", ""SortOrder"")
SELECT
    r.""Id"",
    trim(i.""ingredient""),
    i.""ord""::int
FROM ""Recipes"" r
CROSS JOIN LATERAL unnest(string_to_array(coalesce(r.""IngredientsText"", ''), E'\n')) WITH ORDINALITY AS i(""ingredient"", ""ord"")
WHERE coalesce(trim(i.""ingredient""), '') <> ''
  AND NOT EXISTS (
      SELECT 1 FROM ""RecipeIngredients"" ri WHERE ri.""RecipeId"" = r.""Id""
  );
");

            // Move existing denormalized step text into child rows with deterministic image paths.
            migrationBuilder.Sql(@"
INSERT INTO ""RecipeSteps"" (""RecipeId"", ""StepNumber"", ""Description"", ""ImagePath"")
SELECT
    r.""Id"",
    s.""ord""::int,
    trim(s.""step_text""),
    coalesce(nullif(r.""StepImagesFolder"", ''), nullif(r.""Slug"", ''), 'recipe') || '/step' || s.""ord""::text || '.jpg'
FROM ""Recipes"" r
CROSS JOIN LATERAL unnest(string_to_array(coalesce(r.""StepsText"", ''), E'\n')) WITH ORDINALITY AS s(""step_text"", ""ord"")
WHERE coalesce(trim(s.""step_text""), '') <> ''
  AND NOT EXISTS (
      SELECT 1 FROM ""RecipeSteps"" rs WHERE rs.""RecipeId"" = r.""Id""
  );
");

            migrationBuilder.Sql(@"
ALTER TABLE ""Recipes"" DROP COLUMN IF EXISTS ""IngredientsText"";
ALTER TABLE ""Recipes"" DROP COLUMN IF EXISTS ""StepsText"";
ALTER TABLE ""Recipes"" DROP COLUMN IF EXISTS ""StepImagesFolder"";
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "IngredientsText",
                table: "Recipes",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "StepImagesFolder",
                table: "Recipes",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "StepsText",
                table: "Recipes",
                type: "text",
                nullable: true);

            migrationBuilder.DropTable(name: "RecipeIngredients");
            migrationBuilder.DropTable(name: "RecipeSteps");
        }
    }
}
