// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication.Data;

#nullable disable

namespace WebApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260309195104_RatingAndNews")]
    partial class RatingAndNews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Русская кухня",
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Европейская кухня",
                            Name = "European"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Азиатская кухня",
                            Name = "Asian"
                        });
                });

            modelBuilder.Entity("WebApplication.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageFileName = "news1.png",
                            Summary = "В России предлагают ввести налог на вредные продукты питания.",
                            Title = "Налог на чипсы и газировку"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageFileName = "news2.png",
                            Summary = "Учёные нашли фрукт, который помогает быстрее восстановиться.",
                            Title = "Фрукт против похмелья"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageFileName = "news3.png",
                            Summary = "Исследователи признали безопасным только один вид подсластителя.",
                            Title = "Подсластители под угрозой"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageFileName = "news4.jpg",
                            Summary = "Читайте о традициях и вкусах грузинской кухни.",
                            Title = "История грузинской кухни"
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CookingTime")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<int>("RatingSum")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CookingTime = 20,
                            CreatedAt = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Традиционный русский завтрак из творога",
                            Difficulty = 1,
                            ImageFileName = "syrniki.png",
                            Name = "Сырники",
                            RatingCount = 0,
                            RatingSum = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CookingTime = 60,
                            CreatedAt = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Грузинский суп с говядиной и рисом",
                            Difficulty = 2,
                            ImageFileName = "kharcho.png",
                            Name = "Харчо",
                            RatingCount = 0,
                            RatingSum = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CookingTime = 40,
                            CreatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ароматное блюдо из лесных грибов",
                            Difficulty = 2,
                            ImageFileName = "mushrooms.png",
                            Name = "Грибы в сметане",
                            RatingCount = 0,
                            RatingSum = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CookingTime = 90,
                            CreatedAt = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Украинский свёкольный суп с говядиной",
                            Difficulty = 2,
                            ImageFileName = "borsch.png",
                            Name = "Борщ",
                            RatingCount = 0,
                            RatingSum = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CookingTime = 30,
                            CreatedAt = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Классический русский салат",
                            Difficulty = 1,
                            ImageFileName = "olivie.png",
                            Name = "Оливье",
                            RatingCount = 0,
                            RatingSum = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CookingTime = 15,
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Свежий салат с помидорами, огурцами и фетой",
                            Difficulty = 1,
                            ImageFileName = "greece_salad.png",
                            Name = "Греческий салат",
                            RatingCount = 0,
                            RatingSum = 0
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Recipe", b =>
                {
                    b.HasOne("WebApplication.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApplication.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
