// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication.Data;

#nullable disable

namespace WebApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Русская кухня",
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Европейская кухня",
                            Name = "European"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Азиатская кухня",
                            Name = "Asian"
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CookingTime")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CookingTime = 20,
                            CreatedAt = new DateTime(2026, 2, 20, 16, 23, 43, 67, DateTimeKind.Utc).AddTicks(5042),
                            Description = "Традиционный русский завтрак из творога",
                            Difficulty = 1,
                            ImageFileName = "syrniki.png",
                            Name = "Сырники"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CookingTime = 60,
                            CreatedAt = new DateTime(2026, 2, 22, 16, 23, 43, 67, DateTimeKind.Utc).AddTicks(5051),
                            Description = "Грузинский суп с говядиной и рисом",
                            Difficulty = 2,
                            ImageFileName = "kharcho.png",
                            Name = "Харчо"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CookingTime = 40,
                            CreatedAt = new DateTime(2026, 2, 25, 16, 23, 43, 67, DateTimeKind.Utc).AddTicks(5052),
                            Description = "Ароматное блюдо из лесных грибов",
                            Difficulty = 2,
                            ImageFileName = "mushrooms.png",
                            Name = "Грибы в сметане"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CookingTime = 90,
                            CreatedAt = new DateTime(2026, 2, 23, 16, 23, 43, 67, DateTimeKind.Utc).AddTicks(5054),
                            Description = "Украинский свёкольный суп с говядиной",
                            Difficulty = 2,
                            ImageFileName = "borsch.png",
                            Name = "Борщ"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CookingTime = 30,
                            CreatedAt = new DateTime(2026, 2, 27, 16, 23, 43, 67, DateTimeKind.Utc).AddTicks(5056),
                            Description = "Классический русский салат",
                            Difficulty = 1,
                            ImageFileName = "olivie.png",
                            Name = "Оливье"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CookingTime = 15,
                            CreatedAt = new DateTime(2026, 2, 28, 16, 23, 43, 67, DateTimeKind.Utc).AddTicks(5057),
                            Description = "Свежий салат с помидорами, огурцами и фетой",
                            Difficulty = 1,
                            ImageFileName = "greece_salad.png",
                            Name = "Греческий салат"
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Recipe", b =>
                {
                    b.HasOne("WebApplication.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApplication.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
